#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  5 14:53:13 2017

@author: asurin
"""

def hello ():
    """Print "Hello World" and return None"""
    print("Hello World")
    
hello()
